services:
  rabbitmq:
    image: rabbitmq:management
    container_name: saga-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
  
  postgres:
    image: postgres:17.4-alpine
    container_name: saga-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: newsletter